---
name: pr

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.x'

      - name: npm install
        run: npm install
        working-directory: non-root-path

      - name: npm run build
        run: npm run build
        working-directory: non-root-path
