name: pr

on:
  pull_requests:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.x'

      - name: npm install
        if: steps.check.outputs.changed == 'true'
        run: npm install
        working-directory: non-root-path

      - name: npm run build
        if: steps.check.outputs.changed == 'true'
        run: npm run build
        working-directory: non-root-path
